### ISSUE TITLE
Do not delete tags / releases

### ISSUE THREAD

**Issue by ccoVeille** [chocolacula/gdmd#20]
It's a very bad thing.

It breaks things.

Golang proxy cache a version forever, and it never expires.

https://pkg.go.dev/github.com/chocolacula/gdmd?tab=versions

**Comment by ccoVeille** [comment]
Here is the way to do

https://github.com/ccoVeille/go-safecast/blob/main/go.mod#L5-L7

**Comment by ccoVeille** [comment]
Also, as you code is not yet fully ready. You should use pre-release flag when publishing the tag

**Comment by chocolacula** [comment]
To be honest this is one of disappointing Golang moments. They cache your repo even without your ask but do not allow you to control it, only clumsy retract option.

**Comment by ccoVeille** [comment]
Yes, I know

**Comment by chocolacula** [comment]
retracted 0.1.4
