### ISSUE TITLE
empty .go directory causes a panic

### ISSUE THREAD

**Issue by freakytoad1** [chocolacula/gdmd#3]
For reasons out of my control our internal pipelines create a `.go` directory to put specific files in. Running `gdmd ./` at the top level tries to parse this directory as a file and immediately panics. 

Suggest skipping a parse of a directory.

```go
panic: .go:1:1: expected 'package', found 'EOF'
goroutine 1 [running]:
main.mustParse(...)
	/go/pkg/mod/github.com/chocolacula/gdmd@v0.1.1/cmd/gdmd/parse.go:20
main.Parse({0xc000020e40, 0x23}, {0x0, 0x0}, 0x0)
	/go/pkg/mod/github.com/chocolacula/gdmd@v0.1.1/cmd/gdmd/parse.go:53 +0x8be
main.main()
	/go/pkg/mod/github.com/chocolacula/gdmd@v0.1.1/cmd/gdmd/main.go:53 +0x[35](https://code.epichosted.com/msavino/go-pipeline-testing/-/jobs/6735373#L35)d
```

**Comment by freakytoad1** [comment]
Another suggestion would be to check if the item has a name. If it is just an extension, skip.

`.go` -> skip
`main.go` -> parse

**Comment by chocolacula** [comment]
@freakytoad1 are you sure it's a directory? Because it looks like an empty `.go` file.

**Comment by freakytoad1** [comment]
A mkdir command is used to make it. I do see you are checking for directories in the parse code though. I started to write up a pull request for this edge case but probably won’t get back to it until Monday.

**Comment by chocolacula** [comment]
@freakytoad1 don’t worry, I have a draft with checking a file is not hidden just like go compiler do. It will cover this age case. Will merge it this weekend.

**Comment by chocolacula** [comment]
You could test it in your environment

**Comment by chocolacula** [comment]
@freakytoad1 please check code in your environment from the branch in [this](https://github.com/chocolacula/gdmd/pull/4) PR. I'm sure it's better to skip all hidden files, not only `.go` but `.foo.go` and so on.

**Comment by freakytoad1** [comment]
@chocolacula I'm only able to use versioned releases in this environment unfortunately. Looking over your PR, it seems the fix you provide would work out fine!
