### ISSUE TITLE
an empty folder causes a panic

### ISSUE THREAD

**Issue by freakytoad1** [chocolacula/gdmd#5]
Hitting this in parse.go when a directory doesn't contain any go files (may contain other types of files). This error bubbles up and causes a panic to occur.

```go
	if len(fnames) == 0 && len(pkgs) == 0 {
		return Package{}, EmptyErr
	}
```

Would suggest checking for this error on the function that calls parse and ignoring it?

Difficult to tell what directory is causing this to happen since that isn't included in the error. The project this was ran on seems to have some subdirectories that only contain png or html files. Some other directories do contain .go files.

**Comment by freakytoad1** [comment]
Seems to be happening on projects that don't have any .go files at the root but have subdirectories containing go code instead. A typical server app

**Comment by freakytoad1** [comment]
- cmd
  - main.go
- internal
  - server
    - server.go
- docs
  - docs.go
- Dockerfile
- go.mod
- go.sum

^ This type of directory layout

**Comment by chocolacula** [comment]
How do you call gdmd? It doesn’t go to each directory recursively without ‘-r’ flag. The error you see happens when it didn’t find any .go file in a directory without the flag and all subdirectories with it.

**Comment by freakytoad1** [comment]
Thank you for that information. I did not see that option described anywhere so I assumed it recursed. The `gdmd ./ -r` command works with -r on the end.
