### ISSUE TITLE
index out of range [0] with length 0

### ISSUE THREAD

**Issue by 3052** [chocolacula/gdmd#7]
~~~
> gdmd google-main/play
panic: runtime error: index out of range [0] with length 0
~~~

**Comment by chocolacula** [comment]
What is this repo? Can you share a link? Cannot google it.

**Comment by 3052** [comment]
https://github.com/3052/google

**Comment by 3052** [comment]
problem is here:

https://github.com/chocolacula/gdmd/blob/42681cc7bcd98ff879186c14104a3996ba6a7fa8/cmd/gdmd/types.go#L99-L102

a receiver does not have to have any names, example

~~~go
func (GoogleCheckin) Marshal(device *GoogleDevice) ([]byte, error)
~~~

**Comment by 3052** [comment]
some more examples in this section

https://go.dev/ref/spec#Selectors

**Comment by 3052** [comment]
problem is here:

https://github.com/chocolacula/gdmd/blob/42681cc7bcd98ff879186c14104a3996ba6a7fa8/cmd/gdmd/types.go#L99-L102

a receiver does not have to have any names, example

~~~go
func (GoogleCheckin) Marshal(*GoogleDevice) ([]byte, error)
~~~

as shown here:

~~~
ParameterDecl  = [ IdentifierList ] [ "..." ] Type .
~~~

a parameter can be just a type without an identifier

https://go.dev/ref/spec#ParameterDecl

**Comment by 3052** [comment]
problem is here:

https://github.com/chocolacula/gdmd/blob/42681cc7bcd98ff879186c14104a3996ba6a7fa8/cmd/gdmd/types.go#L99-L102

a parameter can be just a type without an identifier:

~~~
ParameterDecl  = [ IdentifierList ] [ "..." ] Type .
~~~

https://go.dev/ref/spec#ParameterDecl

fix:

~~~go
recv := ""
if f.Decl.Recv != nil {
   if f.Decl.Recv.List[0].Names != nil {
      recv = f.Decl.Recv.List[0].Names[0].Name
   }
}
~~~

**Comment by 3052** [comment]
https://github.com/chocolacula/gdmd/issues/8
